### ISSUE TITLE
Firestore Emulator

### ISSUE THREAD

**Issue by HAV0C101** [gladly-team/next-firebase-auth#322]
Hi, 

I couldn't find any documentation or other issues on this so I thought I would ask

Is it possible to use the firestore emulator with next-firebase-auth?

Thanks in advance :)

**Comment by famu1hundred** [comment]
@HAV0C101 mind sharing how you did this? I'm having the exact same problem. I can get the emulator to work with the Auth & Functions services but not Firestore. The app looks at my production Firestore and not my local so I get Missing or insufficient permissions. Any advice would be helpful!

**Comment by famu1hundred** [comment]
Nvm I figured it out...I was using the next-firebase-auth client instance instead of my own

**Comment by egisz** [comment]
Had same issue, it turned out I forgot that[ NextJs in client side rendering is stripping env variables](https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser) not starting NEXT_PUBLIC_XXX, so in initAuth, you should have to keep this in mind. 
I checked for FIRESTORE_EMULATOR_HOST, which was undefined client side and therefore emulator was not used.
