### ISSUE TITLE
When opening link in new tab, SSR AuthUser not found on initial load

### ISSUE THREAD

**Issue by joeyscarim** [gladly-team/next-firebase-auth#351]
**Description**
When clicking a link to a next-firebase-auth site from another site (Google docs and Basecamp are the two I tested), the SSR function does not initially see the AuthUser token.

**Video:**
https://user-images.githubusercontent.com/13211414/145492578-f52621fe-83c0-4c92-867a-df9e1399eb87.mov

**Versions**
Demo versions:
next-firebase-auth: version: v0.13.5-alpha.0
Firebase JS SDK: v^8.9.1
Next.js: v12.0.2
Was able to reproduce in Chrome latest, firefox latest, and ios safari latest

**To Reproduce**
1. Go to https://nfa-example.vercel.app/ and sign in
2. Click a link to an SSR page from another tab, i.e. https://docs.google.com/document/d/1rk3yVwn8r9ZgTnf8Mvdeqly3ZBU-GlZMQj6cOPcrKh0/edit
3. SSR does not find AuthUser, redirects to login page, then finds auth, and redirects back

**Expected behavior**
Is this the expected behavior? I tested with withAuthUserSSR but had the same results.

**Comment by kmjennison** [comment]
This behavior is determined by the cookie's `SameSite` setting:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite#values

The example app's config currently uses `SameSite=strict`, and thus it's expected behavior.

I don't see much value in the example app remaining strict, though—I'll update it to lax to make the link UX nicer.

**Comment by kmjennison** [comment]
Updated the demo, so this should no longer happen.
