### ISSUE TITLE
Client and server disagree on whether AuthUser has emailVerified

### ISSUE THREAD

**Issue by leebailey88** [gladly-team/next-firebase-auth#406]
**Describe the bug**
When users log in with email / password, the AuthUser initially has `emailVerified == false`;  After clicking the email verification link and refreshing the page, the front end is updated correctly with `emailVerified == true` (acquiring AuthUser via `useAuthUser()`), but the backend still thinks the email is unverified (acquiring the AuthUser in the api via `verifyIdToken();`). If the user logs out and logs back in, the client and server then start to agree that the user is emailVerified.

**Versions**

`next-firebase-auth` version: 0.13.5
Firebase JS SDK: 8.9.1
Next.js: 12.0.7

**To Reproduce**
1. Sign up new user with email/password
2. Send the email verification from the code
3. Click the email verification link, close window
4. Refresh app window

**Expected behavior**
The user should not have to log out and log back in for the server to understand that the user is emailVerified

**Additional context**

**Comment by leebailey88** [comment]
It looks like in your `createAuthUser` you use different methods of determining email verified for client and server based on Firebase Client or Admin SDKs. Firebase should be instantaneously updated though with the `emailVerified`. Could it be there is a cache mechanism somewhere serverside that is not updating until a new session?

**Comment by kmjennison** [comment]
You'll have to force-refresh the Firebase ID token when you want immediate updates to the token. Firebase will otherwise reuse the token until it expires. You can force-refresh the ID token by calling [`getIdToken(true)`](https://firebase.google.com/docs/reference/js/v8/firebase.User#getidtoken) after the email is verified. The AuthUser object also has a `getIdToken` method you can use in the same manner.

Let me know if you run into any problems.
