### ISSUE TITLE
Page Change Delay

### ISSUE THREAD

**Issue by ukanwat** [gladly-team/next-firebase-auth#432]
**Describe the bug**
After install next-firebase-auth, I am noticing a slight delay and some flicker in static pages whenever the page changes. This goes away when I uninstall it. I am guessing that, this is due to the requests to the login api which happens on page navigation. Is there a way to lower this or eradicate this problem?

**Versions**
All

Next.js: 

**To Reproduce**
Just Install normally

**Expected behavior**
Page navigation should be smooth.

**Additional context**

**Comment by kmjennison** [comment]
Please provide a live example with code and, if possible, a video of the issue. Closing until there's more specificity.

Most likely, the flickering is due to your rendering logic. See [`withAuthUser`](https://github.com/gladly-team/next-firebase-auth#withauthuser-options-pagecomponent) options to render even before Firebase has initialized.
