### ISSUE TITLE
Provide better support for Google Cloud native environments

### ISSUE THREAD

**Issue by samos123** [gladly-team/next-firebase-auth#75]
**Is your feature request related to a problem? Please describe.**
When you run on Google Cloud, you often can rely on the default application credentials. So there isn't a need to store the private key in an environment variable. Instead it would be preferred to load the firebase admin using this code:
```
var admin = require('firebase-admin');
var app = admin.initializeApp();
```
For reference see: https://firebase.google.com/docs/admin/setup

**Describe the solution you'd like and how you'd implement it**
Change the behaviour such that when no `firebaseAdminInitConfig` is specified it will initialize the app using the following code:
```
admin.initializeApp()
```

**Is this a breaking change?**
Would this require existing users to change how they're using `next-firebase-auth`?
It wouldn't be a breaking change because existing users that have the firebaseAdminConfig will continue to work as is

I will happily provide a PR for this change if this is something that you would accept.

**Comment by kmjennison** [comment]
This makes sense. However, I'd like to also preserve the error for the users who accidentally don't provide any credentials. Ideally:
* If the user provided a credential, init as we currently do.
* If the user did not provide a credential, try `admin.initializeApp()`. If it fails because of an invalid or missing app credential, throw the existing error (`If not initializing the Firebase admin SDK elsewhere, you must provide "firebaseAdminInitConfig" to next-firebase-auth.`) I'm not sure [what error code](https://firebase.google.com/docs/auth/admin/errors) the admin app uses for a failed init.

Just FYI, as a fairly straightforward workaround, you can initialize Firebase yourself before initializing `next-firebase-auth`. See [the pattern here](https://github.com/gladly-team/next-firebase-auth/discussions/61#discussioncomment-323977).

**Comment by samos123** [comment]
I tried the latest version and this was working out of the box now when setting `useFirebaseAdminDefaultCredential: true,`. Thank you for the great library and making it work easily on GCP environments!

**Comment by kmjennison** [comment]
Wonderful, thanks for the follow-up and kind words!
