### ISSUE TITLE
Invalid custom tokens while using Google authentification

### ISSUE THREAD

**Issue by SaeedHK** [gladly-team/next-firebase-auth#90]
**Describe the bug**

I would like to add Google authentication to the example you provided in the repository. Specifically, I modified `signInOptions` in `example/components/FirebaseAuth.js` as follows:
```
  signInOptions: [
    firebase.auth.GoogleAuthProvider.PROVIDER_ID,
  ],
```
Setting up my firebase config info, when I try to login I get the following error:
```
Error: Problem getting a refresh token: {"error":{"code":400,"message":"INVALID_CUSTOM_TOKEN","errors":[{"message":"INVALID_CUSTOM_TOKEN","domain":"global","reason":"invalid"}]}}
```
I checked the token in https://jwt.io/ and it also raised that the token is invalid.

**Version**

0.13.0-alpha.0

**Comment by qvanderlinden** [comment]
Hi, I am facing the same issue when running [the repo example](https://github.com/gladly-team/next-firebase-auth/tree/main/example). The error occurs when `setAuthCookies` is called on the `pages/api/login` endpoint. Also using version 0.13.0-alpha.0

**Comment by kmjennison** [comment]
Some people have run into this problem because [the Firebase email address was incorrect](https://github.com/gladly-team/next-firebase-auth/discussions/79#discussioncomment-392071). Can you double-check your Firebase config? 

Other people seem to run into this [when their server time is incorrect](https://github.com/firebase/php-jwt/issues/127#issuecomment-291862337).

> I checked the token in https://jwt.io/ and it also raised that the token is invalid.

@SaeedHK If it's invalid, what is wrong with it?

I'll help where I can, though I unfortunately don't have much time to help investigate particular implementation problems.

**Comment by SaeedHK** [comment]
Thank you for your reply. I made a mistake on the Firebase client email. Putting the correct one, solved the problem.

**Comment by rooprob** [comment]
To note, the correct FIREBASE_CLIENT_EMAIL is the Google Cloud IAM Service Account email that matches up with the FIREBASE_PRIVATE_KEY.
